name: Deploy GitHub Pages
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install and build
      run: |
        npm ci
        npm run build --if-present
    - name: setup git repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://ayatk:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
        EMAIL=$(cat ${GITHUB_EVENT_PATH} | jq -r '.commits[0].author.email') && git config --global user.email "${EMAIL}"
        NAME=$(cat ${GITHUB_EVENT_PATH} | jq -r '.commits[0].author.name')  && git config --global user.name "${NAME}"
    - name: deploy github pages
      run: |
        cp CNAME dist/CNAME
        npx gh-pages -d dist -t -m "Build at $(date +'%Y-%m-%dT%H:%M:%S')"
