name: Deploy GitHub Pages
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - name: npm install and build
      run: |
        yarn
        yarn build
    - name: setup git repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://ayatk:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
        EMAIL=$(cat ${GITHUB_EVENT_PATH} | jq -r '.commits[0].author.email') && git config --global user.email "${EMAIL}"
        NAME=$(cat ${GITHUB_EVENT_PATH} | jq -r '.commits[0].author.name')  && git config --global user.name "${NAME}"
    - name: deploy github pages
      run: |
        cp CNAME build/CNAME
        npx gh-pages -d build -t -m "Build at $(date +'%Y-%m-%dT%H:%M:%S')"
